name: First App

on:
  push:
    branches: [ "main" ]

env:
  # Parameters
  MODULO: 1
  NAME: Vanessa

jobs:
  setup-build-publish-deploy:
    name: First App
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Replace Variables
      uses: danielr1996/envsubst-action@1.1.0
      env:
        MODULO: ${{ env.MODULO }}
        NAME: ${{ env.NAME }}
        LAST_NAME: ${{ secrets.LAST_NAME }}
      with:
        input: "${{ github.workspace }}/.github/manifests/template.yaml"
        output: file.yaml

    - name: commands
      run: |-
        cat file.yaml

